services:
  - type: web
    name: webservices-kofi-webhook
    runtime: node
    plan: free
    buildCommand: "true"
    startCommand: node webhooks/kofi-listener.mjs
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: KOFI_VERIFICATION_TOKEN
        sync: false
